language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew
  - ls -lah gradle/wrapper/
  - ls -lah
  - ./gradlew check
script:
  - jdk_switcher use oraclejdk8
  - ./gradlew check
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/